language: cpp
compiler: gcc
os: linux
sudo: required
dist: xenial
install:
  - sudo apt-get update
  - sudo apt-get install curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake git
script:
  - cd depends && make
  - cd .. && ./autogen.sh && ./configure --enable-avx2 --with-gui && make
