language: cpp
compiler: gcc
os: linux
sudo: required
dist: xenial
install:
  - sudo apt-get update
  - sudo apt-get install curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake git
script:
  - cd depends && make -j 4
  - cd .. && ./autogen.sh && ./configure --prefix `pwd`/depends/x86_64-pc-linux-gnu --enable-avx2 --with-gui && make
